"""Generated by organelleverse.capabilities.scaffold. Edit freely."""

from __future__ import annotations


def run(*, value: int = 1):
    return {
        "schema_version": "organelleverse.result.v1",
        "kind": "result",
        "operation_id": 'example.external_capability',
        "scope": "none",
        "status": "ok",
        "metrics": {
        'value': value,
        "doubled": value * 2,
        },
    }
