"""Shared helper: prove a domain's committed bundles are what the generator
produces, without ever writing into the committed tree to find out.

Every ``tests/capabilities/test_restored_<domain>_bundles.py`` file used to
call ``build_domain(..., output_root=_BUNDLE_ROOT)`` - the real, committed
``src/organelleverse/capabilities/`` tree - so running its own "the
generator produces exactly these ids" test rewrote tracked source on every
run. That made the tree self-healing: a bundle mutated or deleted between
commits (by hand, by a bad merge, by disk corruption) would be silently
repaired the moment any test in that domain's file ran, before any other
guard - including the fixture-portability guards in
``test_generated_fixtures_end_to_end.py`` - ever got a chance to see the
mutation.

``assert_regenerated_domain_matches_committed`` closes that: the domain
test now generates into an isolated ``tmp_path`` output root instead, and
this function proves - by real, byte-for-byte comparison, never by
assumption - that what was just generated in isolation is identical to
what is actually committed. Two directions are checked for every bundle
directory: the file *set* must match (an orphaned committed file with
nothing generating it, or a freshly generated file nothing commits, are
both caught by name) and every file's *bytes* must match exactly. This
covers ``capability.toml`` and any ``fixtures/**`` tree the same way - the
helper does not need to know which domains carry fixtures and which do
not.
"""

from __future__ import annotations

from pathlib import Path


def assert_regenerated_domain_matches_committed(
    isolated_output_root: Path,
    committed_bundle_root: Path,
    bundle_dir_names: set[str],
) -> None:
    """Every file the generator just wrote under *isolated_output_root*, for
    each name in *bundle_dir_names*, must be byte-identical to what is
    already committed under *committed_bundle_root* - and neither side may
    have a file the other lacks.
    """
    for dir_name in sorted(bundle_dir_names):
        generated_dir = isolated_output_root / dir_name
        committed_dir = committed_bundle_root / dir_name
        generated_files = {
            path.relative_to(generated_dir).as_posix()
            for path in generated_dir.rglob("*")
            if path.is_file()
        }
        committed_files = {
            path.relative_to(committed_dir).as_posix()
            for path in committed_dir.rglob("*")
            if path.is_file()
        }
        assert generated_files == committed_files, (
            f"{dir_name}: generated and committed file sets differ - "
            f"generated only: {sorted(generated_files - committed_files)}; "
            f"committed only: {sorted(committed_files - generated_files)}"
        )
        for relative_path in sorted(generated_files):
            generated_bytes = (generated_dir / relative_path).read_bytes()
            committed_bytes = (committed_dir / relative_path).read_bytes()
            assert generated_bytes == committed_bytes, (
                f"{dir_name}/{relative_path}: freshly generated bytes differ from committed"
            )


__all__ = ["assert_regenerated_domain_matches_committed"]
