"""examples/external-capability/ must be generated by scaffold(), never hand-written.

Capability Plan 02 Task 3's charter (``.superpowers/sdd/charters/
capability-02-task-3-authoring.md``, deliverable 6) requires one worked
example under ``examples/external-capability/``, generated by ``scaffold()``
*inside a test* so the example can never silently drift from the generator.

This module generates the exact example fresh in a temporary directory on
every test run and:

1. asserts the tree committed at ``examples/external-capability/`` is
   byte-for-byte identical to what ``scaffold()`` just produced -- so a
   hand-edit to the committed copy, or an un-regenerated drift from a future
   ``scaffold()`` change, fails CI immediately; and
2. asserts the freshly generated bundle passes the full
   ``discover -> verify -> trust -> admit -> invoke`` authoring loop proven
   by ``tests/capabilities/test_authoring_loop.py``, forging nothing.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from organelleverse.capabilities.admission import admit_capabilities
from organelleverse.capabilities.discovery import discover_capabilities
from organelleverse.capabilities.index import CapabilityStatus
from organelleverse.capabilities.scaffold import ScaffoldParameter, scaffold
from organelleverse.capabilities.trust import TrustStore, trust
from organelleverse.capabilities.verification import (
    LocalVerificationEnvironment,
    VerificationStore,
    verify_capability,
)
from organelleverse.capabilities.worker import OneShotBundleWorkerExecutor
from organelleverse.core.result import OrganelleResult
from organelleverse.operations.registry import OperationRegistry
from tests._paths import PROJECT_ROOT

EXAMPLE_CAPABILITY_ID = "example.external_capability"
EXAMPLE_TITLE = "External capability example"
EXAMPLE_DESCRIPTION = (
    "A minimal external capability bundle, generated end-to-end by "
    "organelleverse.capabilities.scaffold(...), demonstrating the full "
    "discover -> verify -> trust -> admit -> invoke authoring loop from "
    "outside this repository. Regenerate with `organelleverse-capability "
    "init` or scaffold(...) directly using this test's exact parameters -- "
    "never hand-edit these files."
)
EXAMPLE_PARAMETERS = (ScaffoldParameter(name="value", annotation="int", default=1),)

COMMITTED_EXAMPLE_ROOT = PROJECT_ROOT / "examples" / "external-capability"


def _generate_example(target: Path) -> Path:
    return scaffold(
        target,
        capability_id=EXAMPLE_CAPABILITY_ID,
        title=EXAMPLE_TITLE,
        description=EXAMPLE_DESCRIPTION,
        parameters=EXAMPLE_PARAMETERS,
    )


def _walk_files(root: Path) -> dict[str, bytes]:
    return {
        str(path.relative_to(root)): path.read_bytes()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def test_example_matches_a_fresh_scaffold_byte_for_byte(tmp_path: Path) -> None:
    generated_root = _generate_example(tmp_path / "external-capability")
    assert COMMITTED_EXAMPLE_ROOT.is_dir(), (
        "examples/external-capability/ must be committed; regenerate it with "
        "this test's exact scaffold(...) parameters, never by hand."
    )
    assert _walk_files(generated_root) == _walk_files(COMMITTED_EXAMPLE_ROOT)


def test_example_passes_the_full_authoring_loop_and_invokes_for_real(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setenv("ORGANELLEVERSE_HOME", str(tmp_path / "home"))
    monkeypatch.setenv("ORGANELLEVERSE_CACHE_ROOT", str(tmp_path / "cache"))

    search_root = tmp_path / "capabilities"
    _generate_example(search_root / "external-capability")

    # 1. discover_capabilities(paths=[search_root])
    discovered = discover_capabilities(paths=[search_root])
    entry = discovered.describe(EXAMPLE_CAPABILITY_ID)
    assert entry.execution_identity is not None
    assert entry.status is not CapabilityStatus.ADMITTED

    # 2. verify_capability(id, store=VerificationStore(tmp), environment=<adapter>)
    verification_store = VerificationStore(tmp_path / "verifications")
    environment = LocalVerificationEnvironment(discovered)
    record = verify_capability(
        EXAMPLE_CAPABILITY_ID, store=verification_store, environment=environment
    )
    assert record.capability_id == EXAMPLE_CAPABILITY_ID
    assert record.bundle_content_hash == entry.content_hash
    assert record.execution_identity == entry.execution_identity
    assert record.equivalence == ()  # zero-fixture bundle

    # 3. trust(id, entry.execution_identity, store=TrustStore(tmp))
    trust_store = TrustStore(tmp_path / "trust.json")
    trust(EXAMPLE_CAPABILITY_ID, entry.execution_identity, store=trust_store)

    # 4. admit_capabilities(index, store=...)
    admitted_index = admit_capabilities(discovered, store=verification_store)
    admitted_entry = admitted_index.describe(EXAMPLE_CAPABILITY_ID)
    assert admitted_entry.status is CapabilityStatus.ADMITTED, admitted_entry.diagnostic

    # 5. index.binding_source(trust_store=..., executor=...)
    executor = OneShotBundleWorkerExecutor()
    binding_source = admitted_index.binding_source(trust_store=trust_store, executor=executor)

    # 6. OperationRegistry.invoke(...) -- assert the real returned value.
    registry = OperationRegistry(capability_source=binding_source)
    result = registry.invoke(EXAMPLE_CAPABILITY_ID, input=None, parameters={"value": 21})

    assert isinstance(result, OrganelleResult)
    assert result.metrics["doubled"] == 42
    assert result.metrics["value"] == 21
